Traceback (most recent call last):
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 138, in __init__
    self.data = check_det_dataset(self.args.data)
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/data/utils.py", line 327, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError:
Dataset 'data.yaml' images not found ‚ö†Ô∏è, missing path '/home/eynardmaxime1/Tree_Recognition/datasets/Datasets/valid/images'
Note dataset download directory is '/home/eynardmaxime1/Tree_Recognition/datasets'. You can update this in '/home/eynardmaxime1/.config/Ultralytics/settings.yaml'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    train_yolov8('n')
  File "train.py", line 24, in train_yolov8
    yolo.train(data='data.yaml', epochs=EPOCHS, batch=BATCH_SIZE, lr0=LR,
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 636, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 142, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ‚ùå {e}")) from e
RuntimeError: Dataset 'data.yaml' error ‚ùå
Dataset 'data.yaml' images not found ‚ö†Ô∏è, missing path '/home/eynardmaxime1/Tree_Recognition/datasets/Datasets/valid/images'
Note dataset download directory is '/home/eynardmaxime1/Tree_Recognition/datasets'. You can update this in '/home/eynardmaxime1/.config/Ultralytics/settings.yaml'
Traceback (most recent call last):
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 138, in __init__
    self.data = check_det_dataset(self.args.data)
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/data/utils.py", line 327, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError:
Dataset 'data.yaml' images not found ‚ö†Ô∏è, missing path '/home/eynardmaxime1/Tree_Recognition/datasets/Datasets/valid/images'
Note dataset download directory is '/home/eynardmaxime1/Tree_Recognition/datasets'. You can update this in '/home/eynardmaxime1/.config/Ultralytics/settings.yaml'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    train_yolov8('n')
  File "train.py", line 24, in train_yolov8
    yolo.train(data='data.yaml', epochs=EPOCHS, batch=BATCH_SIZE, lr0=LR,
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 636, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/home/eynardmaxime1/.local/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 142, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ‚ùå {e}")) from e
RuntimeError: Dataset 'data.yaml' error ‚ùå
Dataset 'data.yaml' images not found ‚ö†Ô∏è, missing path '/home/eynardmaxime1/Tree_Recognition/datasets/Datasets/valid/images'
Note dataset download directory is '/home/eynardmaxime1/Tree_Recognition/datasets'. You can update this in '/home/eynardmaxime1/.config/Ultralytics/settings.yaml'
Ultralytics YOLOv8.1.29 üöÄ Python-3.8.10 torch-1.9.0+cu111 CUDA:0 (Tesla T4, 15110MiB)
WARNING ‚ö†Ô∏è Upgrade to torch>=2.0.0 for deterministic training.
[34m[1mengine/trainer: [39m[22mtask=detect, mode=train, model=yolov8n.pt, data=data.yaml, epochs=200, time=None, patience=50, batch=16, imgsz=640, save=True, save_period=10, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train2